spring.application.name=backend

# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/module5
spring.datasource.username=root
spring.datasource.password=9924
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ictbookingroom@gmail.com
spring.mail.password=qnhg qhvt gvya vsvo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

typhoon.api.key=sk-aWU8FOBHfNCumRAmrJfhUblxZ7KvUkpHBSEhuSikqqEah4xO
typhoon.model.name=typhoon-ocr

gemini.api.key=AIzaSyBwmP2UU7TATEpx4POF69w4be-pfTeR8Kc
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent